Repository laurentiucm22/cypressTC, pull requests merged in 2023-01, with the labels that each got.

#1 iangtag
  .gitignore
  README.md
  cypress/e2e/testingChallengeSpec.cy.js
  img.png
Labels: question

#2 added visibility assertion for checksFound list
  cypress/e2e/testingChallengeSpec.cy.js
Labels: enhancement

#3 Indian website, Home Page - test case 2 and 3
  cypress.config.js
  cypress/common/commonMethods.js
  cypress/e2e/NAViangtagTests/Home.cy.js
  cypress/e2e/TCtests/testingChallengeSpec.cy.js
  cypress/utils/constant.js
  cypress/utils/functions.js
  package-lock.json
  package.json
Labels: help wanted

#4 Revert "Indian website, Home Page - test case 2 and 3"
  cypress.config.js
  cypress/common/commonMethods.js
  cypress/e2e/NAViangtagTests/Home.cy.js
  cypress/e2e/testingChallengeSpec.cy.js
  cypress/utils/constant.js
  cypress/utils/functions.js
  package-lock.json
  package.json
Labels: help wanted
